# Generated by Django 2.1.5 on 2019-01-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_commit', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
