dist: xenial
sudo: required
services:
  - docker
env:
  global:
    - COMPOSE_FILE=docker-compose.yml:docker-compose-travis.yml
before_install:
  - docker --version
  - docker-compose --version
  - mkdir codecov # create directory for coverage report, that is mounted as volume
before_script:
  - docker-compose config
  - docker-compose up --build -d
  - docker images
  - docker ps -a
  - docker-compose exec web pip install pipfile-requirements==0.1.0.post0
  - docker-compose exec web bash -c "pipfile2req -d Pipfile.lock > Requirements.txt"
  - docker-compose exec web pip install -r Requirements.txt
  - docker-compose exec web npm install
  - docker-compose exec web npm run build
script:
  - docker-compose exec web pytest --cov-report xml
  - docker-compose exec web pytest --cov-report xml -m "functional" tests/functional/imports/ --cov-append
  - docker-compose exec web pytest --cov-report xml -m "functional and not search" tests/functional/browser --cov-append
  - docker-compose exec web mv coverage.xml codecov/ # move coverage report to directory, that is mounted as volume
  # check if migrations can be applied without errors
  - docker-compose exec web python manage.py migrate
  # check if production settings file throws warnings
  - docker-compose exec web python manage.py check --deploy --settings=config.settings.production
after_success:
  # see: https://docs.codecov.io/docs/testing-with-docker
  - bash <(curl -s https://codecov.io/bash) # send coverage.xml to codecov.io
after_script:
  - docker-compose down
