dist: xenial
sudo: required
language: python
services:
  - docker
python:
  - "3.7"
env:
  global:
  - DISPLAY=:99.0
  - GECKODRIVER_VERSION=0.23.0
addons:
  firefox: latest
before_install:
  - docker --version
  - docker-compose --version
  - curl -L -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
  - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH
  - geckodriver --version
before_script:
  - docker-compose -f "docker-compose.yml" -f "docker-compose-travis.yml" up --build -d
  - docker images
  - docker ps -a
script:
  - docker-compose exec web pytest
  - docker-compose exec web pytest -m "functional" tests/functional/test_system_import.py --cov-append
  - docker-compose exec web pytest -m "functional" tests/functional/test_imports.py --cov-append
  - docker-compose exec web xvfb-run pytest -m "functional" tests/functional/test_search.py --cov-append
#  - xvfb-run pytest -s -m "functional" --driver Firefox --cov-append tests/functional/test_browser.py
after_success:
  - docker-compose exec web codecov
after_script:
  - docker-compose -f "docker-compose.yml" -f "docker-compose-travis.yml" down
