dist: xenial
language: python
python: "3.6"
cache:
  - pip
  - npm
node_js: 10
env:
  global:
  - DISPLAY=:99.0
  - GECKODRIVER_VERSION=0.23.0
  - ELASTICSEARCH_VERSION=2.4.2
addons:
  firefox: latest
before_install:
  - npm i -g npm@6.4.1
  - curl -L -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
  - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH
  - geckodriver --version
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ELASTICSEARCH_VERSION/elasticsearch-$ELASTICSEARCH_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb && sudo service elasticsearch restart
  - sleep 10
  - curl localhost:9200
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run paver copy_secrets_file
  - pipenv run paver setup_frontend
before_script:
  - sleep 10
script:
  - pytest
  - pytest -m "functional" tests/functional/test_system_import.py --cov-append
  - pytest -m "functional" tests/functional/test_imports.py --cov-append
  - xvfb-run pytest -m "functional" tests/functional/test_search.py --cov-append
  - xvfb-run pytest -s -m "functional" --driver Firefox --cov-append tests/functional/test_browser.py
  - python manage.py migrate
after_success:
  - codecov
