version: '2.4'

services:
  web:
    image: paneldata/ddionrails:latest-dev
    command: bash -c "while [ 1 ]; do python /usr/src/app/manage.py runserver_plus --print-sql 0.0.0.0:8000; test $$? -gt 128 && break; done"
    env_file: 
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    volumes:
      - ./ddionrails:/usr/src/app/ddionrails
      - ./config:/usr/src/app/config
      - ./local:/usr/src/app/local
      - ./tests:/usr/src/app/tests
      - ./templates:/usr/src/app/templates
      - ./htmlcov:/usr/src/app/htmlcov
      - ./assets:/usr/src/app/assets
      - ./static/dist:/usr/src/app/static/dist
      - ./webpack.config.js:/usr/src/app/webpack.config.js

  postgres:
    env_file:
      - docker/environments/database.env.example

  elasticsearch:
    ports:
      - 9200:9200

# Uncomment these lines, if you want to use Kibana
#  kibana:
#    image: kibana:4.6.0
#    ports:
#      - 5601:5601
#    networks:
#      - ddi_net

  nginx:
    volumes: 
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf