version: '3.7'

services:
  web:
    build: .
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    # Set your own variables, use of the example files at yout own risk.
    #env_file: 
    #  - docker_environments/django.env.example
    #  - docker_environments/database.env.example
    ports:
      - 8000:8000
    entrypoint: bash /usr/src/app/entrypoint.sh
  postgres:
    image: postgres:11.2-alpine 
    # Set your own variables, use of the example files at yout own risk.
    #env_file:
    #  - docker_environments/database.env.example
  elasticsearch:
    image: elasticsearch:2.2.0
    # These settings are taken from the elastic search installation guide:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
    # I am unclear about their necessity and function, except ES_JAVA_OPTS.
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # Sets the RAM the java VM is allowed to use
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  redis:
    image: redis:4-alpine3.9

volumes:
  elastic_data: