version: '3.7'

services:
  web:
    command: python /usr/src/app/manage.py runserver_plus --print-sql 0.0.0.0:8000
    env_file: 
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    volumes:
      - ./ddionrails:/usr/src/app/ddionrails
      - ./config:/usr/src/app/config
      - ./local:/usr/src/app/local
      - ./tests:/usr/src/app/tests
      - ./templates:/usr/src/app/templates

  postgres:
    env_file:
      - docker/environments/database.env.example
    
  nginx:
    volumes: 
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf