version: '3.7'

services:
  web:
    env_file: 
      - docker/environments/django.env.example
      - docker/environments/database.env.example
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.testing
  postgres:
    env_file:
      - docker/environments/database.env.example
