version: '2.4'

services:
  web:
    env_file: 
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    entrypoint: ./docker/ddionrails/entrypoint.sh
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.testing
      DJANGO_LIVE_TEST_SERVER_ADDRESS: web:9000 # bind live server to a fixed port
    pids_limit: -1
    volumes:
      - ./codecov:/usr/src/app/codecov
      - ./assets:/usr/src/app/assets
      - ./config:/usr/src/app/config
      - ./ddionrails:/usr/src/app/ddionrails
      - ./docker:/usr/src/app/docker
      - ./local:/usr/src/app/local
      - ./static:/usr/src/app/static
      - ./templates:/usr/src/app/templates
      - ./tests:/usr/src/app/tests
      - ./manage.py:/usr/src/app/manage.py
      - ./logging.conf:/usr/src/app/logging.conf
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./package.json:/usr/src/app/package.json
      - ./pavement.py:/usr/src/app/pavement.py
      - ./Pipfile:/usr/src/app/Pipfile
      - ./Pipfile.lock:/usr/src/app/Pipfile.lock
      - ./webpack.config.js:/usr/src/app/webpack.config.js
    ports:
      - 9000 # used for live server test
  postgres:
    env_file:
      - docker/environments/database.env.example

  nginx:
    volumes: 
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf

  selenium:
    image: selenium/standalone-firefox:3.141.59
    networks:
      - ddi_net
    ports:
      - 4444
