version: '3.7'

services:
  web:
    build: ./docker/ddionrails/
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    # Set your own variables, use of the example files at yout own risk.
    entrypoint: bash /usr/src/app/entrypoint.sh
    #env_file:
    #  - docker/environments/django.env
    #  - docker/environments/database.env
    networks:
      ddi_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    ports: 
      - 8000
    volumes: 
      - static:/usr/src/app/static

  postgres:
    image: postgres:11.2-alpine 
    # Set your own variables, use of the example files at yout own risk.
    #env_file:
    #  - docker/environments/database.env
    networks:
      - ddi_net

  elasticsearch:
    image: elasticsearch:2.2.0
    # These settings are taken from the elastic search installation guide:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
    # I am unclear about their necessity and function, except ES_JAVA_OPTS.
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # Sets the RAM the java VM is allowed to use
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - ddi_net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 8000:80
    depends_on: 
      - web
    environment:
      - HOST_NAME=localhost
    networks:
      - ddi_net
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static:/usr/src/app/static

  redis:
    image: redis:4-alpine3.9

volumes:
  elastic_data:
  static:

networks:
  ddi_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"