version: '3.7'

services:
  web:
    env_file: 
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.testing
      DJANGO_LIVE_TEST_SERVER_ADDRESS: web:9000 # bind live server to a fixed port
    volumes:
      - ./codecov:/usr/src/app/codecov
      - ./tests:/usr/src/app/tests
    ports:
      - 9000 # used for live server test
  postgres:
    env_file:
      - docker/environments/database.env.example

  nginx:
    volumes: 
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf

  selenium:
    image: selenium/standalone-firefox:3.141.59
    networks:
      - ddi_net
    ports:
      - 4444
