version: "2.4"

services:
  web:
    image: paneldata/ddionrails:latest-dev
    command: >
      bash -c "
        pipenv install --system --dev &
        npm run build &
        while [ 1 ];
        do 
          python /usr/src/app/manage.py runserver_plus \
            --print-sql 0.0.0.0:8000;
          test $$? -gt 128 && break;
        done"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      selenium-firefox:
        condition: service_started
    entrypoint: ./docker/ddionrails/entrypoint.sh
    env_file:
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    pids_limit: -1
    volumes:
      - ./:/usr/src/app/
      - media:/var/django/media
      - ~/.ssh/docker-dev/:/root/.ssh

  postgres:
    env_file:
      - docker/environments/database.env.example
  nginx:
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
  selenium-firefox:
    image: selenium/standalone-firefox:4.0.0-rc-2-prerelease-20210923
    shm_size: '2gb'
    ports: 
      - 4444
    networks:
      - ddi_net


