version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/ddionrails/Dockerfile
    command: [
            "gunicorn", "config.wsgi",
            "--bind", "0.0.0.0:8000",
            "--error-logfile", "-",
            "--access-logformat",
            "'[gunicorn] %(h)s %(l)s %(u)s %(t)s %(r)s %(s)s %(b)s %(f)s %(a)s'",
            "--access-logfile", "-" ] 
    # Set your own variables, use of the example files at your own risk.
    #env_file:
    #  - docker/environments/django.env
    #  - docker/environments/database.env
    #  - docker/environments/elasticsearch.env
    networks:
      ddi_net:
        # This Address is used in the nginx.example.conf and in the docker/mail/Dockerfile
        # If you want to change it, you have to also change it there.
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    ports: 
      - 8000
    volumes: 
      - static:/usr/src/app/static
    restart: unless-stopped

  postgres:
    image: postgres:11.2-alpine 
    # Set your own variables, use of the example files at yout own risk.
    #env_file:
    #  - docker/environments/database.env
    networks:
      - ddi_net
    volumes:
      # Config
      - ddi-psql-config:/etc/postgresql
      # Data
      - ddi-psql-data:/var/lib/postgresql
      # Logs
      - ddi-psql-logs:/var/log/postgresql

  elasticsearch:
    image: elasticsearch:2.4.6
    # These settings are taken from the elastic search installation guide:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
    # I am unclear about their necessity and function, except ES_JAVA_OPTS.
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # Sets the RAM the java VM is allowed to use
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - ddi_net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  mail:
    build:
      context: ./docker/postfix/
    networks:
      - ddi_net

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    depends_on: 
      - web
    environment:
      - HOST_NAME=127.0.0.1
    networks:
      - ddi_net
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/usr/src/app/static:ro

  redis:
    image: redis:4-alpine3.9
    networks:
      - ddi_net

volumes:
  elastic_data:
  static:
  ddi-psql-config:
  ddi-psql-data:
  ddi-psql-logs:

networks:
  ddi_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
