version: '2.4'

services:
  web:
    env_file: 
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    command: >
      sh -c "
        pipenv install --system --dev &
        npm run build && \
        gunicorn config.wsgi \
        --bind 0.0.0.0:8000 \
        --error-logfile - \
        --access-logfile - \
        --log-level=info"
    entrypoint: ./docker/ddionrails/entrypoint.sh
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.testing
      DJANGO_LIVE_TEST_SERVER_ADDRESS: web:9000 # bind live server to a fixed port
    volumes:
      - ./:/usr/src/app
      - ./codecov:/usr/src/app/codecov
    ports:
      - 9000 # used for live server test
  postgres:
    env_file:
      - docker/environments/database.env.example

  nginx:
    volumes: 
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf

  selenium:
    image: selenium/standalone-firefox:3.141.59
    networks:
      - ddi_net
    ports:
      - 4444
