version: "2.4"

services:
  web:
    image: paneldata/ddionrails:latest-dev
    command: >
      bash -c "
        pipenv install --system --dev &
        npm run build &
        while [ 1 ];
        do 
          python /usr/src/app/manage.py runserver_plus \
            --print-sql 0.0.0.0:8000;
          test $$? -gt 128 && break;
        done"
    entrypoint: ./docker/ddionrails/entrypoint.sh
    env_file:
      - docker/environments/django.env.example
      - docker/environments/database.env.example
      - docker/environments/elasticsearch.env.example
    pids_limit: -1
    volumes:
      - ./:/usr/src/app/
      - media:/var/django/media
      - ~/.ssh/docker-dev/:/root/.ssh
      - ~/.gnupg/docker-dev/:/root/.gnupg/

  postgres:
    env_file:
      - docker/environments/database.env.example

  # Uncomment these lines, if you want to use Kibana
  #  kibana:
  #    image: kibana:4.6.0
  #    ports:
  #      - 5601:5601
  #    networks:
  #      - ddi_net

  nginx:
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
