# Generated by Django 2.2 on 2019-04-09 07:58

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import ddionrails.base.mixins
import ddionrails.elastic.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("label_de", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
                ("repo", models.CharField(blank=True, max_length=255)),
                ("webhook_token", models.CharField(blank=True, max_length=255)),
                ("current_commit", models.CharField(blank=True, max_length=255)),
                ("config", models.TextField(blank=True)),
                ("files_url", models.CharField(blank=True, max_length=255)),
            ],
            options={"abstract": False},
            bases=(
                ddionrails.elastic.mixins.ModelMixin,
                ddionrails.base.mixins.ModelMixin,
                models.Model,
            ),
        )
    ]
