# Generated by Django 3.1.2 on 2020-10-16 08:50
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration of the study (JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="topiclist",
            name="topiclist",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Topics of the related study (JSON)",
                null=True,
            ),
        ),
    ]
