# Generated by Django 2.2.3 on 2019-07-11 14:53
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
# Pylint is not fully compatible with isort
# pylint: disable=ungrouped-imports

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="study",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the study (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the study (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
    ]
