# Generated by Django 2.2.1 on 2019-05-21 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="study", options={"verbose_name_plural": "Studies"}
        ),
        migrations.RemoveField(model_name="study", name="files_url"),
        migrations.RemoveField(model_name="study", name="webhook_token"),
        migrations.AlterField(
            model_name="study",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration of the study (JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="current_commit",
            field=models.CharField(
                blank=True,
                help_text="Commit hash of the last metadata import. This field is automatically filled by DDI on Rails",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the study (Markdown)"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Label of the study (English)",
                max_length=255,
                verbose_name="Label (English)",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Label of the study (German)",
                max_length=255,
                null=True,
                verbose_name="Label (German)",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Name of the study", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="repo",
            field=models.CharField(
                blank=True,
                help_text="Reference to the Git repository without definition of the protocol (e.g. https)",
                max_length=255,
            ),
        ),
    ]
