# Generated by Django 2.2.1 on 2019-06-04 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0002_auto_20190521_1258")]

    operations = [
        migrations.AddField(
            model_name="study",
            name="topic_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Topic languages of the study (Array)",
                size=None,
            ),
        )
    ]
