# Generated by Django 2.2.1 on 2019-06-05 15:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("studies", "0002_auto_20190521_1258")]

    operations = [
        migrations.CreateModel(
            name="TopicList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topiclist",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=list,
                        help_text="Topics of the related study (JSON)",
                        null=True,
                    ),
                ),
                (
                    "study",
                    models.OneToOneField(
                        blank=True,
                        help_text="OneToOneField to studies.Study",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topiclist",
                        to="studies.Study",
                    ),
                ),
            ],
        )
    ]
