# Generated by Django 3.2.4 on 2021-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0002_auto_20201016_0850")]

    operations = [
        migrations.AlterField(
            model_name="topiclist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        )
    ]
