# Generated by Django 2.2.1 on 2019-06-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_topiclist"),
        ("studies", "0003_study_topic_languages"),
    ]

    operations = []
