# Generated by Django 4.0.6 on 2022-08-09 08:53
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_topiclist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="menu_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Integer value to sort study in UI"
            ),
        ),
    ]
