# Generated by Django 2.2.2 on 2019-06-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0004_merge_20190611_1416")]

    operations = [
        migrations.AddField(
            model_name="study",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="DOI of the study (DOI only, not the URL to the DOI)",
                max_length=255,
                verbose_name="DOI",
            ),
        )
    ]
