# Generated by Django 4.2.3 on 2023-07-27 12:30
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0004_study_menu_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="version",
            field=models.CharField(blank=True),
        ),
    ]
