# Generated by Django 5.1.4 on 2025-02-24 13:08
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_study_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="pin_reference",
            field=models.CharField(
                blank=True,
                help_text="Git reference to pin the study repository to.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="current_commit",
            field=models.CharField(
                blank=True,
                help_text="Commit hash of the last metadata import. ",
                max_length=255,
            ),
        ),
    ]
