# Generated by Django 5.2.1 on 2025-06-19 12:11
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0006_study_pin_reference_alter_study_current_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="webhook_secret",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
    ]
