# Generated by Django 2.1.7 on 2019-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='name_cs',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
