# Generated by Django 2.1.3 on 2018-12-03 13:13

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0007_auto_20180926_1719")]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]
            ),
        ),
    ]
