# Generated by Django 2.1.3 on 2018-12-19 15:39

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_variable_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]),
        ),
    ]
