# Generated by Django 2.1.3 on 2018-12-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20181203_1413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='release',
            name='study',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
    ]
