# Generated by Django 2.1.7 on 2019-03-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('study', 'name')},
        ),
    ]
