# Generated by Django 2.1.7 on 2019-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20190329_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
