# Generated by Django 2.1.3 on 2018-12-03 13:11

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20161018_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]),
        ),
    ]
