# Generated by Django 3.2.4 on 2021-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        )
    ]
