# Generated by Django 2.2.1 on 2019-05-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="context_study",
            field=models.ForeignKey(
                help_text="Foreign key to studies.Study",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_attachments",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to data.Dataset",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="data.Dataset",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to instruments.Instrument",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="instruments.Instrument",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to instruments.Question",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="instruments.Question",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="study",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to studies.Study",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="url",
            field=models.TextField(
                blank=True, help_text="Link (URL) to the attachment", verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="url_text",
            field=models.TextField(
                blank=True,
                help_text="Text to be displayed for the link",
                verbose_name="URL text",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="variable",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to data.Variable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="data.Variable",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="abstract",
            field=models.TextField(blank=True, help_text="Abstract of the publication"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="author",
            field=models.TextField(blank=True, help_text="Name(s) of the author(s)"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="cite",
            field=models.TextField(
                blank=True, help_text="Suggested citation of the publication"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.TextField(
                blank=True,
                help_text="DOI of the publication (DOI only, not the URL to the DOI)",
                verbose_name="DOI",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Name of the publication", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="studies",
            field=models.TextField(
                blank=True,
                help_text="Description of studies/data sources used in the publication",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="study",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to studies.Study",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="sub_type",
            field=models.CharField(
                blank=True,
                help_text="Type of the publication (e.g., journal article or dissertation)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(blank=True, help_text="Title of the publication"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="url",
            field=models.TextField(
                blank=True,
                help_text="URL referencing the publication",
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.TextField(blank=True, help_text="Year of publication"),
        ),
    ]
