# Generated by Django 2.2.3 on 2019-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Year of publication", null=True
            ),
        )
    ]
