# Generated by Django 5.0.8 on 2024-09-26 07:40
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_alter_attachment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="sub_type",
        ),
        migrations.AddField(
            model_name="publication",
            name="type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of the publication (e.g., journal article or dissertation)",
                max_length=255,
            ),
        ),
    ]
