# Generated by Django 2.2.4 on 2019-08-13 14:17
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
# Pylint is not fully compatible with isort
# pylint: disable=ungrouped-imports

# Help texts are often too long here but this file is not meant for reading
# anyways. The models themselves are, the lines there follow the 90 char limit.
# pylint: disable=line-too-long

from django.db import migrations, models

import ddionrails.base.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_commit", models.CharField(blank=True, max_length=255)),
            ],
            bases=(ddionrails.base.mixins.ImportPathMixin, models.Model),
        )
    ]
