# Generated by Django 2.2.10 on 2020-02-26 11:52
# pylint: disable-all

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("base", "0002_news")]

    operations = [
        migrations.AlterModelOptions(name="news", options={"verbose_name_plural": "news"})
    ]
