# Generated by Django 4.2.1 on 2023-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_auto_20210624_0828"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="content_de",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
