# Generated by Django 5.1.4 on 2025-02-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_news_content_de_alter_news_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="System",
        ),
    ]
