# Generated by Django 2.2.2 on 2019-06-28 13:18

import uuid

import django.db.models.deletion
from django.db import migrations, models

import config.validators
import ddionrails.base.mixins
import ddionrails.elastic.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [("studies", "__first__")]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Name of the topic (Lowercase)",
                        max_length=255,
                        unique=True,
                        validators=[config.validators.validate_lowercase],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the topic (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the topic (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Topic",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="concepts.Topic",
                        verbose_name="Parent (concepts.Topic)",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="Foreign key to studies.Study",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.Study",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the topic (German)",
                        max_length=255,
                        verbose_name="Label (German)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the Topic. Dependent on the associated study",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={"unique_together": {("study", "name")}},
            bases=(models.Model, ddionrails.base.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name="AnalysisUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the AnalysisUnit.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the analysis unit (Lowercase)",
                        max_length=255,
                        unique=True,
                        validators=[config.validators.validate_lowercase],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the analysis unit (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the analysis unit (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the analysis unit (German)",
                        max_length=255,
                        verbose_name="Label (German)",
                    ),
                ),
            ],
            bases=(models.Model, ddionrails.base.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the Concept.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the concept (Lowercase)",
                        max_length=255,
                        unique=True,
                        validators=[config.validators.validate_lowercase],
                        verbose_name="concept name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the concept (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the concept (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        help_text="ManyToMany relation to concepts.Topic",
                        related_name="concepts",
                        to="concepts.Topic",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the concept (German)",
                        max_length=255,
                        verbose_name="Label (German)",
                    ),
                ),
            ],
            bases=(
                models.Model,
                ddionrails.base.mixins.ModelMixin,
                ddionrails.elastic.mixins.ModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the Period. Dependent on the associated Study.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the period (Lowercase)",
                        max_length=255,
                        validators=[config.validators.validate_lowercase],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the period (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the period (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "definition",
                    models.CharField(
                        blank=True, help_text="Definition of the period", max_length=255
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="Foreign key to studies.Study",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="studies.Study",
                    ),
                ),
            ],
            options={"unique_together": {("study", "name")}},
            bases=(models.Model, ddionrails.base.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name="ConceptualDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the ConceptualDataset.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the conceptual dataset (Lowercase)",
                        max_length=255,
                        unique=True,
                        validators=[config.validators.validate_lowercase],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the conceptual dataset (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the conceptual dataset (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the conceptual dataset (German)",
                        max_length=255,
                        verbose_name="Label (German)",
                    ),
                ),
            ],
            bases=(models.Model, ddionrails.base.mixins.ModelMixin),
        ),
    ]
