# Generated by Django 2.2.3 on 2019-07-11 14:53
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
# Pylint is not fully compatible with isort
# pylint: disable=ungrouped-imports

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concepts", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="period", name="definition"),
        migrations.AddField(
            model_name="analysisunit",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the analysis unit (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the concept (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AddField(
            model_name="conceptualdataset",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the conceptual dataset (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the period (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Label of the period (German)",
                max_length=255,
                verbose_name="Label (German)",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the topic (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AlterField(
            model_name="analysisunit",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the analysis unit (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
        migrations.AlterField(
            model_name="concept",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the concept (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
        migrations.AlterField(
            model_name="conceptualdataset",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the conceptual dataset (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the period (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the topic (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
    ]
