# Generated by Django 2.1.3 on 2018-11-28 12:23

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20160923_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the concept using Markdown.'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='label',
            field=models.CharField(blank=True, help_text='Label (English) of the concept.', max_length=255),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(help_text='Name of the concept.', max_length=255, unique=True, validators=[ddionrails.validators.validate_lowercase], verbose_name='concept name'),
        ),
    ]
