# Generated by Django 2.1.3 on 2018-12-03 12:56

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20181128_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the concept.', max_length=255, unique=True, validators=[ddionrails.validators.validate_lowercase], verbose_name='concept name'),
        ),
    ]
