# Generated by Django 2.2.3 on 2019-07-19 14:05
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
# Pylint is not fully compatible with isort
# pylint: disable=ungrouped-imports

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0001_initial"),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the basket (Lowercase)",
                        max_length=255,
                        validators=[config.validators.validate_lowercase],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the basket",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the basket (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="Foreign key to studies.Study",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets",
                        to="studies.Study",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Foreign key to auth.User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the script", max_length=255),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Label of the script", max_length=255
                    ),
                ),
                (
                    "generator_name",
                    models.CharField(
                        default="soep-stata",
                        help_text=(
                            "Name of the selected Script generator (e.g. soep-stata)"
                        ),
                        max_length=255,
                    ),
                ),
                ("settings", models.TextField(help_text="Settings of the script")),
                (
                    "basket",
                    models.ForeignKey(
                        help_text="Foreign key to workspace.Basket",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.Basket",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="BasketVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basket",
                    models.ForeignKey(
                        help_text="Foreign key to workspace.Basket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets_variables",
                        to="workspace.Basket",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        help_text="Foreign key to data.Variable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baskets_variables",
                        to="data.Variable",
                    ),
                ),
            ],
            options={"unique_together": {("basket", "variable")}},
        ),
        migrations.AddField(
            model_name="basket",
            name="variables",
            field=models.ManyToManyField(
                help_text="ManyToMany relation to data.Variable",
                through="workspace.BasketVariable",
                to="data.Variable",
            ),
        ),
        migrations.AlterUniqueTogether(name="basket", unique_together={("user", "name")}),
    ]
