# Generated by Django 2.2.5 on 2019-10-16 14:53
# pylint: disable=C0111,C0103

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workspace", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="basketvariable",
            name="variable",
            field=models.ForeignKey(
                help_text="Foreign key to data.Variable",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="baskets_variables",
                to="data.Variable",
            ),
        )
    ]
