# Generated by Django 3.0.5 on 2020-04-22 05:32
# pragma: no cover
# pylint: disable-all
# type: ignore
# nosec

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_auto_20191128_0909"),
        ("workspace", "0002_auto_20191016_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketvariable",
            name="variable",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Foreign key to data.Variable",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="baskets_variables",
                to="data.Variable",
            ),
        )
    ]
