# Generated by Django 3.0.5 on 2020-04-24 12:52
# pragma: no cover
# pylint: disable-all
# type: ignore
# nosec

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0001_initial"), ("workspace", "0003_auto_20200422_0532")]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="study",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Foreign key to studies.Study",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="baskets",
                to="studies.Study",
            ),
        )
    ]
