# Generated by Django 3.0.6 on 2020-06-08 07:02
# pragma: no cover
# pylint: disable-all
# type: ignore
# nosec

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_auto_20191128_0909"),
        ("studies", "0001_initial"),
        ("workspace", "0004_auto_20200424_1252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="study",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Foreign key to studies.Study",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="basketvariable",
            name="variable",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Foreign key to data.Variable",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets_variables",
                to="data.Variable",
            ),
        ),
    ]
