# Generated by Django 4.1.2 on 2022-10-26 07:43
# pylint: disable=all

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0004_study_menu_order"),
        ("workspace", "0006_auto_20210624_0828"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptMetadata",
            fields=[
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="studies.study",
                    ),
                ),
                ("metadata", models.JSONField(default={})),
            ],
        ),
    ]
