# Generated by Django 2.1.4 on 2019-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20181219_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='period',
        ),
        migrations.AddField(
            model_name='publication',
            name='studies',
            field=models.TextField(blank=True),
        ),
    ]
