# Generated by Django 2.1.4 on 2019-01-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20190110_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date',
            new_name='year',
        ),
    ]
