# Generated by Django 2.2.7 on 2019-11-29 09:36
# pylint: disable-all

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concepts", "0001_initial"), ("instruments", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.Period",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="concepts.Period",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="instruments.Instrument",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sort_id",
            field=models.IntegerField(
                blank=True,
                help_text="Sort order of questions within one instrument",
                verbose_name="Sort ID",
            ),
        ),
    ]
