# Generated by Django 3.0.7 on 2020-06-16 12:39
# pragma: no cover
# pylint: disable-all
# type: ignore
# nosec

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concepts", "0001_initial"), ("instruments", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="period",
                to="concepts.Period",
            ),
        )
    ]
