# Generated by Django 4.0.4 on 2022-06-03 07:24
# pylint: disable-all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="has_questions",
            field=models.BooleanField(
                default=False,
                help_text="Flag if instrument has Questions associated with it.",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="mode",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The procedure, technique, or mode of inquiry used to attain the data.",
                verbose_name="Mode of inquiry.",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="type",
            field=models.JSONField(
                blank=True,
                default={},
                help_text="Categorization for instruments",
                verbose_name="Instrument type",
            ),
        ),
    ]
