# Generated by Django 2.2.1 on 2019-05-28 08:01

import django.db.models.deletion
from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    dependencies = [("instruments", "0002_auto_20190514_1532")]

    operations = [
        migrations.AlterField(
            model_name="conceptquestion",
            name="concept",
            field=models.ForeignKey(
                help_text="Foreign key to concepts.Concept",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concepts_questions",
                to="concepts.Concept",
            ),
        ),
        migrations.AlterField(
            model_name="conceptquestion",
            name="question",
            field=models.ForeignKey(
                help_text="Foreign key to instruments.Question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concepts_questions",
                to="instruments.Question",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="analysis_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.AnalysisUnit",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruments",
                to="concepts.AnalysisUnit",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the topic (Markdown)",
                verbose_name="Description (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Label of the instrument (English)",
                max_length=255,
                verbose_name="Label (English)",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the instrument (Lowercase)",
                max_length=255,
                validators=[config.validators.validate_lowercase],
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.Period",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruments",
                to="concepts.Period",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="study",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to studies.Study",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruments",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the topic (Markdown)",
                verbose_name="Description (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="label",
            field=models.TextField(
                blank=True,
                help_text="Label of the question (English)",
                verbose_name="Label (English)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="label_de",
            field=models.TextField(
                blank=True,
                help_text="Label of the question (German)",
                verbose_name="Label (German)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the question (Lowercase)",
                max_length=255,
                validators=[config.validators.validate_lowercase],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sort_id",
            field=models.IntegerField(
                blank=True,
                help_text="Sort order of questions within one instrument",
                null=True,
                verbose_name="Sort ID",
            ),
        ),
        migrations.AlterField(
            model_name="questionvariable",
            name="question",
            field=models.ForeignKey(
                help_text="Foreign key to instruments.Question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_variables",
                to="instruments.Question",
            ),
        ),
        migrations.AlterField(
            model_name="questionvariable",
            name="variable",
            field=models.ForeignKey(
                help_text="Foreign key to data.Variable",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_variables",
                to="data.Variable",
            ),
        ),
    ]
