# Generated by Django 3.1.2 on 2020-10-16 08:50
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("instruments", "0002_question_period")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Items are elements in a question",
                null=True,
            ),
        )
    ]
