# Generated by Django 3.2.4 on 2021-06-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("instruments", "0003_auto_20201016_0850")]

    operations = [
        migrations.AlterField(
            model_name="conceptquestion",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="instruments.instrument",
            ),
        ),
        migrations.AlterField(
            model_name="questionvariable",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
