# Generated by Django 2.2.1 on 2019-06-04 11:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("instruments", "0003_auto_20190528_0801")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="items",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=list,
                help_text="Items are elements in a question",
                null=True,
            ),
        )
    ]
