# Generated by Django 4.1.3 on 2022-11-17 10:16
# pylint: disable-all

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_dataset_folder_dataset_primary_key"),
        ("instruments", "0003_instrument_datasets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemVariable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Foreign key to instruments.Question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="instruments.questionitem",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        help_text="Foreign key to data.Variable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="data.variable",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "variable")},
            },
        ),
    ]
