# Generated by Django 2.2.2 on 2019-06-24 12:18

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("instruments", "0004_question_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=2)),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="instruments.Question",
                    ),
                ),
            ],
        )
    ]
