# Generated by Django 5.0.8 on 2024-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0004_itemvariable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="items",
            field=models.JSONField(
                default=list, help_text="Items are elements in a question"
            ),
        ),
    ]
