# Generated by Django 2.2.2 on 2019-06-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    replaces = [('instruments', '0005_questionimage'), ('instruments', '0006_auto_20190617_1046')]

    dependencies = [
        ('filer', '__first__'),
        ('instruments', '0004_question_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=2)),
                ('image', filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.FILER_IMAGE_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='instruments.Question')),
            ],
        ),
    ]
