# pylint: disable=all
# Generated by Django 3.2.5 on 2021-09-13 11:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("instruments", "0004_auto_20210624_0828")]

    operations = [
        migrations.CreateModel(
            name="QuestionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the question. Dependent on the associated instrument.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("txt", "Information Text"),
                            ("cat", "Multiple-answer multiple choice"),
                            ("bin", "Single-answer multiple choice"),
                            ("int", "Integer"),
                            ("chr", "Open-ended"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "label",
                    models.TextField(
                        blank=True,
                        help_text="Label of the question (English)",
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "label_de",
                    models.TextField(
                        blank=True,
                        help_text="Label of the question (German)",
                        verbose_name="Label (German)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the question (Markdown, English)",
                        verbose_name="Description (Markdown, English)",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Description of the question (Markdown, German)",
                        verbose_name="Description (Markdown, German)",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        blank=True,
                        help_text="Position of the question item within one question.",
                        null=True,
                        verbose_name="Item position",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instruments.question",
                    ),
                ),
            ],
        )
    ]
