# pylint: disable=all
# Generated by Django 3.2.6 on 2021-09-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("instruments", "0005_questionitem")]

    operations = [
        migrations.AlterField(
            model_name="questionitem",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_items",
                to="instruments.question",
            ),
        )
    ]
