# Generated by Django 3.2.12 on 2022-03-23 08:43
# pylint: disable-all
# type: ignore
# nosec

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0005_questionitem_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="images",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
