# Generated by Django 2.2.2 on 2019-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("instruments", "0005_questionimage")]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Label of the instrument (German)",
                max_length=255,
                verbose_name="Label (German)",
            ),
        )
    ]
