# pylint: disable=all
# Generated by Django 3.2.6 on 2021-09-14 10:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("instruments", "0006_alter_questionitem_question")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="instruction",
            field=models.TextField(
                blank=True,
                help_text="Optional german question instruction.",
                verbose_name="Instruction German",
            ),
        ),
        migrations.AlterField(
            model_name="questionitem",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                help_text="UUID of the QuestionItem. dependent on the associated Question.",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
