# Generated by Django 3.2.12 on 2022-03-31 09:24
# pylint: disable-all

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0006_question_images"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionImage",
        ),
    ]
