# pylint: disable=all
# Generated by Django 3.2.6 on 2021-09-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("instruments", "0010_questionitem_name"),
        ("instruments", "0011_auto_20210915_0748"),
        ("instruments", "0012_auto_20210915_0854"),
        ("instruments", "0013_rename_item_type_questionitem_scale"),
    ]

    dependencies = [("instruments", "0009_auto_20210914_1236")]

    operations = [
        migrations.AddField(
            model_name="questionitem",
            name="name",
            field=models.TextField(
                help_text="Identifying name of the item.", verbose_name="Item name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionitem",
            name="goto",
            field=models.TextField(
                blank=True,
                help_text="Describes which question item should follow this question item.",
                null=True,
                verbose_name="Goto (Output Filter)",
            ),
        ),
        migrations.AddField(
            model_name="questionitem",
            name="input_filter",
            field=models.TextField(
                blank=True,
                help_text="Describes which question items lead to the inclusion of this question item.",
                null=True,
                verbose_name="Input Filter",
            ),
        ),
        migrations.AlterField(
            model_name="questionitem",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Position of the question item within one question.",
                verbose_name="Item position",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionitem",
            name="instruction",
            field=models.TextField(
                blank=True,
                help_text="Instruction given for this item.",
                verbose_name="Instruction",
            ),
        ),
        migrations.AddField(
            model_name="questionitem",
            name="instruction_de",
            field=models.TextField(
                blank=True,
                help_text="Instruction given for this item. (German)",
                verbose_name="Instruction",
            ),
        ),
        migrations.RenameField(
            model_name="questionitem", old_name="type", new_name="scale"
        ),
    ]
