# Generated by Django 2.1.7 on 2019-03-22 11:41

import ddionrails.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import elastic.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, validators=[ddionrails.validators.validate_lowercase])),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='studies.Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(elastic.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BasketVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets_variables', to='workspace.Basket')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets_variables', to='data.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('generator_name', models.CharField(default='soep-stata', max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('settings', models.TextField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Basket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='variables',
            field=models.ManyToManyField(through='workspace.BasketVariable', to='data.Variable'),
        ),
        migrations.AlterUniqueTogether(
            name='basketvariable',
            unique_together={('basket', 'variable')},
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'name')},
        ),
    ]
