# Generated by Django 2.1.5 on 2019-01-17 13:28

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_auto_20170529_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[ddionrails.validators.validate_lowercase]),
        ),
    ]
