# Generated by Django 2.2b1 on 2019-02-19 16:27

import ddionrails.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20190117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=255, validators=[ddionrails.validators.validate_lowercase]),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
