# Generated by Django 2.1.7 on 2019-03-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_auto_20190307_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='security_token',
        ),
    ]
