# Generated by Django 2.1.5 on 2019-01-15 12:14

import ddionrails.mixins
from django.db import migrations, models
import elastic.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('repo', models.CharField(blank=True, max_length=255)),
                ('webhook_token', models.CharField(blank=True, max_length=255)),
                ('current_commit', models.CharField(blank=True, max_length=255)),
                ('config', models.TextField(blank=True)),
                ('files_url', models.CharField(blank=True, max_length=255)),
            ],
            bases=(elastic.mixins.ModelMixin, ddionrails.mixins.ModelMixin, models.Model),
        ),
    ]
