# Generated by Django 2.1.7 on 2019-03-22 11:41

import ddionrails.mixins
from django.db import migrations, models
import django.utils.timezone
import elastic.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('label_de', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('repo', models.CharField(blank=True, max_length=255)),
                ('webhook_token', models.CharField(blank=True, max_length=255)),
                ('current_commit', models.CharField(blank=True, max_length=255)),
                ('config', models.TextField(blank=True)),
                ('files_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(elastic.mixins.ModelMixin, ddionrails.mixins.ModelMixin, models.Model),
        ),
    ]
