# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='label_de',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
