# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_study_label_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='label_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
