# Generated by Django 2.1.3 on 2018-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20180926_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='organization',
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
