# Generated by Django 2.2.2 on 2019-06-26 14:15

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models

import ddionrails.base.mixins
import ddionrails.elastic.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "__first__"),
        ("concepts", "0001_initial"),
        ("filer", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the dataset", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the dataset (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the dataset (German",
                        max_length=255,
                        null=True,
                        verbose_name="Label (German)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the dataset (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "analysis_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.AnalysisUnit",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="concepts.AnalysisUnit",
                    ),
                ),
                (
                    "conceptual_dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.ConceptualDataset",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="concepts.ConceptualDataset",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Period",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="concepts.Period",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to studies.Study",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="studies.Study",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the dataset. Dependent on the associated study.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={"unique_together": {("study", "name")}},
            bases=(ddionrails.base.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the variable. Dependent on the associated dataset.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the variable", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the variable (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the variable (German)",
                        max_length=255,
                        null=True,
                        verbose_name="Label (German)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the variable (Markdown)",
                        verbose_name="Description (Markdown)",
                    ),
                ),
                (
                    "description_long",
                    models.TextField(
                        blank=True,
                        help_text="Extended description of the variable (Markdown)",
                        verbose_name="Extended description (Markdown)",
                    ),
                ),
                (
                    "sort_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Sort order of variables within one dataset",
                        null=True,
                        verbose_name="Sort ID",
                    ),
                ),
                (
                    "image_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to a related image",
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Concept",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="concepts.Concept",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to data.Dataset",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="data.Dataset",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Period",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="concepts.Period",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=list,
                        help_text="Categories of the variable(JSON)",
                        null=True,
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        blank=True,
                        help_text="Scale of the variable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "statistics",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics of the variable(JSON)",
                        null=True,
                    ),
                ),
            ],
            options={"unique_together": {("name", "dataset")}},
            bases=(
                ddionrails.elastic.mixins.ModelMixin,
                ddionrails.base.mixins.ModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Transformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        help_text="Foreign key to data.Variable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_variables",
                        to="data.Variable",
                        verbose_name="Origin (data.Variable)",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Foreign key to data.Variable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_variables",
                        to="data.Variable",
                        verbose_name="Target (data.Variable)",
                    ),
                ),
            ],
            options={"unique_together": {("origin", "target")}},
        ),
    ]
