# Generated by Django 3.2.12 on 2022-03-31 09:39
# pylint: disable-all

import uuid

import django.db.models.deletion
from django.db import migrations, models

import ddionrails.base.mixins


class Migration(migrations.Migration):

    replaces = [
        ("data", "0001_initial"),
        ("data", "0002_auto_20191127_0829"),
        ("data", "0003_auto_20191128_0909"),
        ("data", "0004_auto_20201016_0850"),
        ("data", "0005_alter_transformation_id"),
        ("data", "0006_variable_statistics_type"),
        ("data", "0007_variable_statistics_flag"),
        ("data", "0008_auto_20220331_0924"),
    ]

    initial = True

    dependencies = [
        ("studies", "0001_initial"),
        ("concepts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the dataset. Dependent on the associated study.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the dataset", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the dataset (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the dataset (German)",
                        max_length=255,
                        null=True,
                        verbose_name="Label (German)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the dataset (Markdown, English)",
                        verbose_name="Description (Markdown, English)",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Description of the dataset (Markdown, German)",
                        verbose_name="Description (Markdown, German)",
                    ),
                ),
                (
                    "analysis_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.AnalysisUnit",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="concepts.analysisunit",
                    ),
                ),
                (
                    "conceptual_dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.ConceptualDataset",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="concepts.conceptualdataset",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Period",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="concepts.period",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to studies.Study",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "unique_together": {("study", "name")},
            },
            bases=(ddionrails.base.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID of the variable. Dependent on the associated dataset.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the variable", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label of the variable (English)",
                        max_length=255,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        blank=True,
                        help_text="Label of the variable (German)",
                        max_length=255,
                        null=True,
                        verbose_name="Label (German)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the variable (Markdown, English)",
                        verbose_name="Description (Markdown, English)",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Description of the variable (Markdown, German)",
                        verbose_name="Description (Markdown, German)",
                    ),
                ),
                (
                    "description_long",
                    models.TextField(
                        blank=True,
                        help_text="Extended description of the variable (Markdown)",
                        verbose_name="Extended description (Markdown)",
                    ),
                ),
                (
                    "sort_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Sort order of variables within one dataset",
                        null=True,
                        verbose_name="Sort ID",
                    ),
                ),
                (
                    "image_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to a related image",
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics of the variable(JSON)",
                        null=True,
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        blank=True,
                        help_text="Scale of the variable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Categories of the variable(JSON)",
                        null=True,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Concept",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="concepts.concept",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to data.Dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="data.dataset",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Foreign key to concepts.Period",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="concepts.period",
                    ),
                ),
                (
                    "statistics_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("categorical", "Categorical"),
                            ("numerical", "Numerical"),
                            ("ordinal", "Ordinal"),
                        ],
                        null=True,
                    ),
                ),
                ("statistics_flag", models.BooleanField(default=False)),
                ("images", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "unique_together": {("name", "dataset")},
            },
            bases=(ddionrails.base.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Transformation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "origin",
                    models.ForeignKey(
                        help_text="Foreign key to data.Variable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_variables",
                        to="data.variable",
                        verbose_name="Origin (data.Variable)",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Foreign key to data.Variable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_variables",
                        to="data.variable",
                        verbose_name="Target (data.Variable)",
                    ),
                ),
            ],
            options={
                "unique_together": {("origin", "target")},
            },
        ),
    ]
