# Generated by Django 2.2.3 on 2019-07-11 14:53
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
# Pylint is not fully compatible with isort
# pylint: disable=ungrouped-imports

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the dataset (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AddField(
            model_name="variable",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the variable (Markdown, German)",
                verbose_name="Description (Markdown, German)",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the dataset (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Label of the dataset (German)",
                max_length=255,
                null=True,
                verbose_name="Label (German)",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the variable (Markdown, English)",
                verbose_name="Description (Markdown, English)",
            ),
        ),
    ]
