# Generated by Django 2.2.7 on 2019-11-27 08:29
# pylint: disable-all

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="image_de",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variable_image_de",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variable_image",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
