# Generated by Django 2.2.1 on 2019-05-28 08:27

import django.db.models.deletion
from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    dependencies = [("data", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="analysis_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.AnalysisUnit",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="concepts.AnalysisUnit",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="boost",
            field=models.FloatField(
                blank=True,
                help_text="Boost factor to be used in search (Elasticsearch)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="conceptual_dataset",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.ConceptualDataset",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="concepts.ConceptualDataset",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the dataset (Markdown)",
                verbose_name="Description (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Label of the dataset (English)",
                max_length=255,
                verbose_name="Label (English)",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Label of the dataset (German",
                max_length=255,
                null=True,
                verbose_name="Label (German)",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the dataset (Lowercase)",
                max_length=255,
                validators=[config.validators.validate_lowercase],
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.Period",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="concepts.Period",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="study",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to studies.Study",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="studies.Study",
            ),
        ),
        migrations.AlterField(
            model_name="transformation",
            name="origin",
            field=models.ForeignKey(
                help_text="Foreign key to data.Variable",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_variables",
                to="data.Variable",
                verbose_name="Origin (data.Variable)",
            ),
        ),
        migrations.AlterField(
            model_name="transformation",
            name="target",
            field=models.ForeignKey(
                help_text="Foreign key to data.Variable",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_variables",
                to="data.Variable",
                verbose_name="Target (data.Variable)",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.Concept",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="concepts.Concept",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to data.Dataset",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="data.Dataset",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the variable (Markdown)",
                verbose_name="Description (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="description_long",
            field=models.TextField(
                blank=True,
                help_text="Extended description of the variable (Markdown)",
                verbose_name="Extended description (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="image_url",
            field=models.TextField(
                blank=True, help_text="URL to a related image", verbose_name="Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Label of the variable (English)",
                max_length=255,
                verbose_name="Label (English)",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Label of the variable (German)",
                max_length=255,
                null=True,
                verbose_name="Label (German)",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Name of the variable", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Foreign key to concepts.Period",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="concepts.Period",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="sort_id",
            field=models.IntegerField(
                blank=True,
                help_text="Sort order of variables within one dataset",
                null=True,
                verbose_name="Sort ID",
            ),
        ),
    ]
