# Generated by Django 4.1.7 on 2023-04-18 11:10
# pylint: disable-all

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_dataset_folder_dataset_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="pid",
            field=models.TextField(default="", verbose_name="Persistent identifier"),
        ),
    ]
