# Generated by Django 3.1.2 on 2020-10-16 08:50
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0003_auto_20191128_0909")]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="categories",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Categories of the variable(JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="statistics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Statistics of the variable(JSON)",
                null=True,
            ),
        ),
    ]
