# Generated by Django 2.2.2 on 2019-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190614_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='scale',
            field=models.CharField(blank=True, help_text='Scale of the variable', max_length=255, null=True),
        ),
    ]
