# Generated by Django 5.2.7 on 2025-12-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_dataset_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="harmonization",
            field=models.BooleanField(
                default=False, verbose_name="Is harmonization variable"
            ),
        ),
        migrations.AddField(
            model_name="variable",
            name="is_harmonized",
            field=models.BooleanField(
                default=False, verbose_name="Variable is harmonized into another variable"
            ),
        ),
        migrations.AddField(
            model_name="variable",
            name="long_variable",
            field=models.BooleanField(
                default=False, verbose_name="Is longitudinal variable"
            ),
        ),
        migrations.CreateModel(
            name="Sibling",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sibling_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.variable"
                    ),
                ),
                (
                    "sibling_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siblings",
                        to="data.variable",
                    ),
                ),
            ],
        ),
    ]
