# Generated by Django 6.0.4 on 2026-04-29 09:27
# pylint: disable-all

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_variable_harmonization_variable_is_harmonized_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variable",
            name="image_url",
        ),
    ]
