# Generated by Django 3.2.12 on 2022-02-15 09:37
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_transformation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="statistics_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("categorical", "Categorical"),
                    ("numerical", "Numerical"),
                    ("ordinal", "Ordinal"),
                ],
                null=True,
            ),
        ),
    ]
