# Generated by Django 3.2.12 on 2022-02-28 10:49
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_variable_statistics_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="statistics_flag",
            field=models.BooleanField(default=False),
        ),
    ]
