name: Docker

on:
  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Before install
        run: |
          docker --version
          docker-compose --version
          mkdir codecov
      - name: Before install
        run: |
          docker-compose config
          docker-compose up --build -d
          docker images
          docker ps -a
          docker-compose exec web pip install pipfile-requirements==0.1.0.post0
          docker-compose exec web bash -c \
          '{ pipfile2req Pipfile.lock & pipfile2req -d Pipfile.lock; } > Requirements.txt'
          docker-compose exec web pip install -r Requirements.txt
          docker-compose exec web npm install
          docker-compose exec web npm run build
      - name: Run tests
        run: |
          docker-compose exec web pytest --cov-report xml --cov --cov-report html --cov-branch
          docker-compose exec web pytest --cov-report xml --cov --cov-report html --cov-branch \
          -m "functional" tests/functional/imports/ --cov-append
          docker-compose exec web pytest --cov-report xml --cov --cov-report html --cov-branch \
          -m "functional and not search" tests/functional/browser --cov-append
          # move coverage report to directory, that is mounted as volume
          docker-compose exec web mv coverage.xml codecov/
          # check if migrations can be applied without errors
          docker-compose exec web python manage.py migrate
         # check if production settings file throws warnings
         docker-compose exec web python manage.py check --deploy --settings=config.settings.production
