# Generated by Django 3.2.9 on 2021-11-30 13:17
# pylint: disable=invalid-name
# pylint: disable=missing-docstring

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("data", "0005_alter_transformation_id")]

    operations = [
        migrations.CreateModel(
            name="IndependentVariable",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("labels", models.JSONField()),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.variable"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariableStatistic",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "plot_type",
                    models.TextField(
                        choices=[
                            ("categorical", "Categorical"),
                            ("numerical", "Numerical"),
                            ("ordinal", "Ordinal"),
                        ]
                    ),
                ),
                ("statistics", models.TextField()),
                ("independent_variable_names", models.JSONField(default=[])),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "independent_variables",
                    models.ManyToManyField(
                        blank=True, null=True, to="statistics.IndependentVariable"
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics_data",
                        to="data.variable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatisticsMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField()),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics_metadata",
                        to="data.variable",
                    ),
                ),
            ],
        ),
    ]
