# Generated by Django 3.2.8 on 2021-11-15 13:02
# pylint: disable=invalid-name
# pylint: disable=missing-docstring

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("data", "0005_alter_transformation_id")]

    operations = [
        migrations.CreateModel(
            name="VariableStatistic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plot_type",
                    models.TextField(
                        choices=[
                            ("categorical", "Categorical"),
                            ("numerical", "Numerical"),
                            ("ordinal", "Ordinal"),
                        ]
                    ),
                ),
                ("statistics", models.TextField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.variable"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndependentVariables",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("labels", models.JSONField()),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.variable"
                    ),
                ),
            ],
        ),
    ]
