# Generated by Django 3.2.12 on 2022-03-01 06:35
# pylint: disable=all

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variablestatistic",
            name="statistics",
            field=models.FileField(upload_to="statistic_files/"),
        ),
    ]
