# Generated by Django 5.0.2 on 2024-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0002_alter_variablestatistic_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="independentvariable",
            name="values",
            field=models.JSONField(default=list),
        ),
    ]
