# Generated by Django 5.0.3 on 2024-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0003_independentvariable_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("metadata", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
