# Generated by Django 5.0.6 on 2024-06-12 09:08
# pylint: disable=all

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0003_independentvariable_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variablestatistic",
            name="independent_variables",
        ),
        migrations.RemoveField(
            model_name="statisticsmetadata",
            name="variable",
        ),
        migrations.RemoveField(
            model_name="variablestatistic",
            name="variable",
        ),
        migrations.DeleteModel(
            name="IndependentVariable",
        ),
        migrations.DeleteModel(
            name="StatisticsMetadata",
        ),
        migrations.DeleteModel(
            name="VariableStatistic",
        ),
    ]
