from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView

from .views import (
    account_overview,
    add_concept,
    add_variable,
    basket_delete,
    basket_detail,
    basket_list,
    basket_new,
    basket_search,
    basket_to_csv,
    register,
    remove_concept,
    remove_variable,
    script_delete,
    script_detail,
    script_new,
    script_new_lang,
    script_raw,
    user_delete,
)

app_name = "workspace"

urlpatterns = [
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), {"next_page": "/"}),
    path("register/", register, name="register"),
    path("delete_account/", user_delete),
    path("password_reset/", PasswordResetView.as_view()),
    path("account/", account_overview, name="account_overview"),
    path("baskets/", basket_list, name="basket_list"),
    path("baskets/new", basket_new, name="basket_list"),
    path("baskets/<int:basket_id>/csv", basket_to_csv),
    path("baskets/<int:basket_id>/search", basket_search),
    path("baskets/<int:basket_id>/delete", basket_delete),
    path(
        "baskets/<int:basket_id>/add/<int:variable_id>/",
        add_variable,
        name="add_variable",
    ),
    path(
        "baskets/<int:basket_id>/remove/<int:variable_id>/",
        remove_variable,
        name="remove_variable",
    ),
    path(
        "baskets/<int:basket_id>/add_concept/<int:concept_id>/",
        add_concept,
        name="add_concept",
    ),
    path(
        "baskets/<int:basket_id>/remove_concept/<int:concept_id>/",
        remove_concept,
        name="remove_concept",
    ),
    path("baskets/<int:basket_id>", basket_detail, name="basket"),
    path("baskets/<int:basket_id>/scripts/new/<slug:generator_name>", script_new_lang),
    path("baskets/<int:basket_id>/scripts/new", script_new),
    path("baskets/<int:basket_id>/scripts/<int:script_id>/delete", script_delete),
    path(
        "baskets/<int:basket_id>/scripts/<int:script_id>",
        script_detail,
        name="script_detail",
    ),
    path("baskets/<int:basket_id>/scripts/<int:script_id>/raw", script_raw),
]
#
# urlpatterns = [
#     url(r"^login/$", LoginView.as_view(redirect_authenticated_user=True), name="login"),
#     url(r"^logout/$", LogoutView.as_view(), {"next_page": "/"}),
#     url(r'^register/$', register, name="register"),
#     url(r'^delete_account/$', user_delete),
#     url(r'^password_reset/$', PasswordResetView.as_view()),
#     url(r'^account/$', account_overview, name="account_overview"),
#     url(r'^baskets/$', basket_list, name="basket_list"),
#     url(r'^baskets/new$', basket_new, name="basket_list"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/csv$', basket_to_csv),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/search$', basket_search),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/delete$', basket_delete),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/add/(?P<variable_id>[0-9]+)/$',
#         add_variable, name="add_variable"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/remove/(?P<variable_id>[0-9]+)/$',
#         remove_variable, name="remove_variable"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/add_concept/(?P<concept_id>[0-9]+)/$',
#         add_concept, name="add_concept"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/remove_concept/(?P<concept_id>[0-9]+)/$',
#         remove_concept, name="remove_concept"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)$', basket_detail, name="basket"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/scripts/new/(?P<generator_name>[0-9a-z_-]+)$', script_new_lang),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/scripts/new$', script_new),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/scripts/(?P<script_id>[0-9]+)/delete$', script_delete),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/scripts/(?P<script_id>[0-9]+)$',
#         script_detail, name="script_detail"),
#     url(r'^baskets/(?P<basket_id>[0-9]+)/scripts/(?P<script_id>[0-9]+)/raw$',
#         script_raw),
# ]
